/* Generated By:JavaCC: Do not edit this line. X12LangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface X12LangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int ISA = 3;
  /** RegularExpression Id. */
  int GS = 4;
  /** RegularExpression Id. */
  int ST = 5;
  /** RegularExpression Id. */
  int SE = 6;
  /** RegularExpression Id. */
  int GE = 7;
  /** RegularExpression Id. */
  int IEA = 8;
  /** RegularExpression Id. */
  int REF = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int PRV = 11;
  /** RegularExpression Id. */
  int NM1 = 12;
  /** RegularExpression Id. */
  int TYPE_INTEGER = 13;
  /** RegularExpression Id. */
  int TYPE_DOUBLE = 14;
  /** RegularExpression Id. */
  int TYPE_STRING = 15;
  /** RegularExpression Id. */
  int TYPE_BOOLEAN = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int MINUS = 20;
  /** RegularExpression Id. */
  int DIVIDE = 21;
  /** RegularExpression Id. */
  int MULTIPLY = 22;
  /** RegularExpression Id. */
  int TERMINATOR = 23;
  /** RegularExpression Id. */
  int INTEGER = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int QUOTED_STRING = 27;
  /** RegularExpression Id. */
  int VARIABLE = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"isa\"",
    "\"gs\"",
    "\"st\"",
    "\"se\"",
    "\"ge\"",
    "\"iea\"",
    "\"ref\"",
    "\"eq\"",
    "\"prv\"",
    "\"nm1\"",
    "\"int\"",
    "\"double\"",
    "\"string\"",
    "\"bool\"",
    "<DIGIT>",
    "<LETTER>",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"~\"",
    "<INTEGER>",
    "<DOUBLE>",
    "<BOOLEAN>",
    "<QUOTED_STRING>",
    "<VARIABLE>",
    "\":\"",
  };

}
